### ISSUE TITLE
Projects 섹션 구현

### ISSUE THREAD

**Issue by AAminha** [AAminha/Portfolio-Minha#9]
# ISSUE ✅ : FEATURE

## 📖 DESCRIPTION

Projects 섹션 구현

## 🖼️ Figma View

![image](https://github.com/user-attachments/assets/f3a3c5c6-c7a6-4d01-8493-c58eb7e43b5c)

## ✨ TODO

- [x] Projects 섹션 구현
  - [x] Project 카드 구현
  - ~~프로젝트 상세 페이지 연결~~ => #14 
  - ~~프로젝트 상세 페이지 구현~~ => #14 
- [x] 헤더 메뉴 연결
